# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - full-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: full-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - prod-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: yarn install --production
      - save_cache:
          paths:
            - node_modules
          key: prod-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: yarn run build
      - run: ./scripts/deploy.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
